In [1]:
import numpy as np 

## 1. Tạo 2D numarray

In [3]:
with open('C:\\code\\gitpythonnangcao\\baitap pỵthon\\chuong3\\baseball_2D.txt','r',encoding='utf-8-sig') as file:
    for i in file:
        data= i.replace('[','').replace(']','').split(',')
np_baseball = np.array(data, dtype=float)
np_baseball = np_baseball.reshape(-1,2)
np_baseball[:5]

array([[ 74., 180.],
       [ 74., 215.],
       [ 72., 210.],
       [ 72., 210.],
       [ 73., 188.]])

In [4]:
np_baseball.dtype

dtype('float64')

## 2. In Giá Trị Dòng Thứ 50

In [5]:
np_baseball[50]

array([ 73., 200.])

## 3. tạo numpy array np_weight

In [6]:
np_weight = np_baseball[:,0]
np_weight[:5]

array([74., 74., 72., 72., 73.])

## 4. chiều cao vận động viên thứ 124

In [7]:
np_height = np_baseball[:,1]

In [8]:
np_height[124]

np.float64(210.0)

## 5. chiều cao và cân nặng trung bình

In [9]:
print("chiều cao trung bình của các cầu thủ là: ",np.mean(np_height))
print("cân nặng trung bình của các cầu thủ là: ",np.mean(np_weight))

chiều cao trung bình của các cầu thủ là:  201.34876847290641
cân nặng trung bình của các cầu thủ là:  73.6896551724138


## 6

## em thấy mối tương quan giữa chiều cao và cân nặng là tương quan thuận