In [18]:
import numpy as np 

## 1

In [19]:
with open('C:\\code\\gitpythonnangcao\\baitap pỵthon\\chuong3\\heights_1.txt','r',encoding = 'utf-8-sig') as file:
    for i in file:
        data = i.replace('[','').replace(']','').split(',')
arr_height = np.array(data,dtype = float)
arr_height

array([74., 74., 72., ..., 75., 75., 73.])

In [20]:
arr_height.dtype

dtype('float64')

## 2

In [21]:
with open('C:\\code\\gitpythonnangcao\\baitap pỵthon\\chuong3\\weights_1.txt','r',encoding='utf-8-sig') as file:
    for i in file:
        data = i.replace('[','').replace(']','').split(',')
arr_weight = np.array(data,dtype=float)
arr_weight

array([180., 215., 210., ..., 205., 190., 195.])

In [22]:
arr_weight.dtype

dtype('float64')

## 3

In [23]:
# Quy Đổi sang m
arr_height_m = arr_height *0.0254
arr_height_m[:5]

array([1.8796, 1.8796, 1.8288, 1.8288, 1.8542])

## 4

In [24]:
# Quy đỏi sang kg
arr_weight_kg = arr_weight*0.453592
arr_weight_kg[:5]

array([81.64656 , 97.52228 , 95.25432 , 95.25432 , 85.275296])

## 5

In [25]:
arr_bmi = arr_weight_kg/(arr_height_m*arr_height_m)
arr_bmi[:5]

array([23.11037639, 27.60406069, 28.48080465, 28.48080465, 24.80333518])

## 6

In [26]:
# cân nặng ở index thứ 50
arr_weight_kg[50]

np.float64(90.7184)

## 7

In [27]:
arr_height_m_100 = arr_height_m[100:111]
arr_height_m_100

array([1.8542, 1.8796, 1.8288, 1.8542, 1.7526, 1.8288, 1.8542, 1.905 ,
       1.905 , 1.8542, 1.8288])

## 8

In [28]:
# các cầu thủ có bmi <21
bmi_under21 = arr_bmi[arr_bmi<21]
bmi_under21

array([20.54255679, 20.54255679, 20.69282047, 20.69282047, 20.34343189,
       20.34343189, 20.69282047, 20.15883472, 19.4984471 , 20.69282047,
       20.9205219 ])

## 9

In [29]:
print("chiều cao trung bình của các cầu thủ là:",arr_height_m.mean(),'m')
print("cân nặng trung bình của các cầu thủ là:",arr_weight_kg.mean(),'kg')


chiều cao trung bình của các cầu thủ là: 1.8717172413793102 m
cân nặng trung bình của các cầu thủ là: 91.33019058916256 kg


## 10

In [30]:
print("chiều cao lớn nhất của các cầu thủ là:",arr_height_m.max(),'m')
print("cân nặng lớn nhất của các cầu thủ là:",arr_weight_kg.max(),'kg')


chiều cao lớn nhất của các cầu thủ là: 2.1082 m
cân nặng lớn nhất của các cầu thủ là: 131.54167999999999 kg


## 11

In [31]:
print("chiều cao nhỏ nhất của các cầu thủ là:",arr_height_m.min(),'m')
print("cân nặng nhỏ nhất của các cầu thủ là:",arr_weight_kg.min(),'kg')


chiều cao nhỏ nhất của các cầu thủ là: 1.7018 m
cân nặng nhỏ nhất của các cầu thủ là: 68.0388 kg
